# site settings

title: Rutu Mulkar
description: ""
taglong: lifelong student, in pursuit of knowledge
# tagshort: Jekyll theme
# url: https://cvless.netlify.app
baseurl: ""
# permalink: pretty
repo: https://github.com/username/username.github.io

# author settings

author:
  name: Rutu Mulkar
  email: me@rutumulkar.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

# pagination:
#   enabled: true
#   per_page: 1
#   sort_reverse: true
#   permalink: /:num/
#   title: ":title &middot; Page :num"
