# Site
name: "Dr. Rutu Mulkar"
title: "Rutu Mulkar"
logo: 'assets/images/logo.png'
favicon: 'assets/images/root2.png'
# baseurl: 
url: 'https://rutumulkar.com'
# webpage: rutumulkar.com
google_analytics: 'UA-64523004-1'
disqus: 'datasciencetoolbox'
mailchimp-list: 'https://ticary.us13.list-manage.com/subscribe/post?u=64e382ea2426e22ee909aff02&amp;id=f0936d6c78'

# https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /blog/:year/:title/

# Authors
authors:
  rutum:
    name: Rutu Mulkar
    display_name: Rutu Mulkar
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: me@rutumulkar.com
    twitter: https://twitter.com/rutumulkar

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/


# Other
markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

redcarpet:
  extensions: [strikethrough, tables]
  
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9977753901275849"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
